languages:
  Ruby: true
exclude_paths:
- "Gemfile.lock"
- "bin"
- "db"
- "test"
engines:
  duplication:
    enabled: true
    exclude_fingerprints:
    - ddf7a8fb13a555a05723c4d2a25c7fdf
    - 7957abd9de79ab206473abf4a4a9cdb1
    config:
      languages:
      - ruby
